// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"; //Loads env variables from .env file
import { defineConfig } from "prisma/config"; //Used to define and validate Prisma configuration

export default defineConfig({
  schema: "prisma/schema.prisma", //Location of Prisma schema file which defines db structure
  migrations: {
    path: "prisma/migrations", //Folder where Prisma stores migration files
  },
  datasource: {
    url: process.env["DATABASE_URL"], //Reads the database URL from the .env file
  },
});
